""".bashrc management: add/remove/update PYTHONPATH and PATH blocks."""

from __future__ import annotations

import shutil
from pathlib import Path

START_MARKER = "# >>> py-trkpac managed >>>"
END_MARKER = "# <<< py-trkpac managed <<<"


def _home_relative(target_path: str) -> str:
    """Express target_path via $HOME when possible, for portability."""
    home = Path.home()
    try:
        rel = Path(target_path).relative_to(home)
        return f"$HOME/{rel}"
    except ValueError:
        # target_path is not under $HOME, use absolute
        return target_path


def _build_block(target_path: str) -> str:
    """Build the shell config block for a given target path."""
    path_expr = _home_relative(target_path)

    return (
        f"{START_MARKER}\n"
        f'export PATH="{path_expr}/bin:$PATH"\n'
        f'export PYTHONPATH="{path_expr}${{PYTHONPATH:+:$PYTHONPATH}}"\n'
        f"{END_MARKER}"
    )


def _read_shell_config(config_path: Path) -> str:
    if not config_path.exists():
        return ""
    return config_path.read_text()


def _has_block(content: str) -> bool:
    return START_MARKER in content and END_MARKER in content


def _remove_block(content: str) -> str:
    """Remove the managed block from content."""
    lines = content.splitlines(keepends=True)
    result = []
    inside = False
    for line in lines:
        if line.rstrip() == START_MARKER:
            inside = True
            continue
        if line.rstrip() == END_MARKER:
            inside = False
            continue
        if not inside:
            result.append(line)
    return "".join(result)


def _backup(config_path: Path) -> Path | None:
    """Create a one-time backup of the shell config. Returns backup path or None if already backed up."""
    backup_path = config_path.parent / f"{config_path.name}.py-trkpac-backup"
    if not backup_path.exists() and config_path.exists():
        shutil.copy2(config_path, backup_path)
        return backup_path
    return None


def add_to_shell(target_path: str, config_path: Path) -> bool:
    """Add the py-trkpac block to the shell config. Returns True if modified."""
    content = _read_shell_config(config_path)
    if _has_block(content):
        return False

    _backup(config_path)

    block = _build_block(target_path)
    # Add a newline before block if file doesn't end with one
    if content and not content.endswith("\n"):
        content += "\n"
    content += f"\n{block}\n"
    config_path.write_text(content)
    return True


def remove_from_shell(config_path: Path) -> bool:
    """Remove the py-trkpac block from the shell config. Returns True if modified."""
    content = _read_shell_config(config_path)
    if not _has_block(content):
        return False

    content = _remove_block(content)
    config_path.write_text(content)
    return True


LAUNCHER_MARKER = "# py-trkpac launcher (managed)"


def _build_launcher(import_root: str) -> str:
    """Build the version-independent CLI launcher script.

    Unlike pip's generated console-script (a hard ``#!/usr/bin/python3.X``
    stub that dangles when the OS replaces the interpreter), this delegates
    to whatever ``python3`` is current and points PYTHONPATH at the
    directory py-trkpac actually lives in (``import_root`` is the parent of
    the ``py_trkpac`` package — e.g. a standalone ``~/.local/share``
    location, the managed dir, or a source checkout's ``src/``). py-trkpac
    is stdlib-only, so it keeps importing across Python upgrades with no
    reinstall regardless of which model is used.
    """
    path_expr = _home_relative(import_root)
    return (
        "#!/usr/bin/env bash\n"
        f"{LAUNCHER_MARKER} — interpreter-version independent.\n"
        "# Regenerated by `py-trkpac init`. Edit the package, not this file.\n"
        f'export PYTHONPATH="{path_expr}${{PYTHONPATH:+:$PYTHONPATH}}"\n'
        'exec python3 -m py_trkpac "$@"\n'
    )


def write_launcher(import_root: str, bin_dir: Path | None = None) -> tuple[Path, str]:
    """Install the resilient launcher to ``bin_dir`` (default ~/.local/bin).

    ``import_root`` is the directory that must be on PYTHONPATH for
    ``python3 -m py_trkpac`` to work — i.e. the parent of the running
    ``py_trkpac`` package.

    Returns (path, status) where status is one of:
      - "unchanged": an identical managed launcher already existed
      - "written":   no launcher existed, one was created
      - "replaced":  a different file existed; it was backed up and replaced
    """
    if bin_dir is None:
        bin_dir = Path.home() / ".local" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)

    launcher_path = bin_dir / "py-trkpac"
    content = _build_launcher(import_root)

    status = "written"
    if launcher_path.exists():
        existing = launcher_path.read_text(errors="replace")
        if existing == content:
            return launcher_path, "unchanged"
        backup = launcher_path.parent / f"{launcher_path.name}.py-trkpac-backup"
        if not backup.exists():
            shutil.copy2(launcher_path, backup)
        status = "replaced"

    # Replace via unlink so we overwrite a dangling symlink target safely.
    if launcher_path.is_symlink() or launcher_path.exists():
        launcher_path.unlink()
    launcher_path.write_text(content)
    launcher_path.chmod(0o755)
    return launcher_path, status


def update_shell(target_path: str, config_path: Path) -> bool:
    """Update the py-trkpac block with a new target path. Returns True if modified."""
    content = _read_shell_config(config_path)
    if _has_block(content):
        content = _remove_block(content)

    _backup(config_path)

    block = _build_block(target_path)
    if content and not content.endswith("\n"):
        content += "\n"
    content += f"\n{block}\n"
    config_path.write_text(content)
    return True
